var cities = [
  {
    city: 'aracaju',
    to: [
      {city: 'aracaju', km: 0},
      {city: 'belem',   km: 2079},
      {city: 'belo_horizonte', km: 1578},
      {city: 'boa_vista', km: 6000},
      {city: 'brasilia', km: 1652},
      {city: 'campo_grande', km: 2765},
      {city: 'cuiaba', km: 2775},
      {city: 'curitiba', km: 2595},
      {city: 'florianopolis', km: 2892},
      {city: 'fortaleza', km: 1183},
      {city: 'goiania', km: 1848},
      {city: 'joao_pessoa', km: 611},
      {city: 'maceio', km: 294},
      {city: 'manaus', km: 5215},
      {city: 'natal', km: 788},
      {city: 'palmas', km: 1662},
      {city: 'porto_alegre', km: 3296},
      {city: 'porto_velho', km: 4230},
      {city: 'recife', km: 501},
      {city: 'rio_branco', km: 4763},
      {city: 'rio_de_janeiro', km: 1855},
      {city: 'salvador', km: 356},
      {city: 'sao_luis', km: 1578},
      {city: 'sao_paulo', km: 2187},
      {city: 'teresina', km: 1142},
      {city: 'vitoria', km: 1408}
    ]
  },
  {
    city: 'belem',
    to: [
      {city: 'aracaju', km: 2079},
      {city: 'belem',   km: 0},
      {city: 'belo_horizonte', km: 2824},
      {city: 'boa_vista', km: 6083},
      {city: 'brasilia', km: 2120},
      {city: 'campo_grande', km: 2942},
      {city: 'cuiaba', km: 2941},
      {city: 'curitiba', km: 3193},
      {city: 'florianopolis', km: 3500},
      {city: 'fortaleza', km: 1301},
      {city: 'goiania', km: 2017},
      {city: 'joao_pessoa', km: 2161},
      {city: 'maceio', km: 2173},
      {city: 'manaus', km: 5298},
      {city: 'natal', km: 2108},
      {city: 'palmas', km: 1283},
      {city: 'porto_alegre', km: 3852},
      {city: 'porto_velho', km: 4397},
      {city: 'recife', km: 2074},
      {city: 'rio_branco', km: 4931},
      {city: 'rio_de_janeiro', km: 3250},
      {city: 'salvador', km: 2100},
      {city: 'sao_luis', km: 806},
      {city: 'sao_paulo', km: 2933},
      {city: 'teresina', km: 947},
      {city: 'vitoria', km: 3108}
    ]
  },
  {
    city: 'belo_horizonte',
    to: [
      {city: 'aracaju', km: 1578},
      {city: 'belem',   km: 2824},
      {city: 'belo_horizonte', km: 0},
      {city: 'boa_vista', km: 4736},
      {city: 'brasilia', km: 716},
      {city: 'campo_grande', km: 1453},
      {city: 'cuiaba', km: 1594},
      {city: 'curitiba', km: 1004},
      {city: 'florianopolis', km: 1301},
      {city: 'fortaleza', km: 2528},
      {city: 'goiania', km: 906},
      {city: 'joao_pessoa', km: 2171},
      {city: 'maceio', km: 1854},
      {city: 'manaus', km: 3951},
      {city: 'natal', km: 2348},
      {city: 'palmas', km: 1690},
      {city: 'porto_alegre', km: 1712},
      {city: 'porto_velho', km: 3050},
      {city: 'recife', km: 2061},
      {city: 'rio_branco', km: 3584},
      {city: 'rio_de_janeiro', km: 434},
      {city: 'salvador', km: 1372},
      {city: 'sao_luis', km: 2738},
      {city: 'sao_paulo', km: 586},
      {city: 'teresina', km: 2302},
      {city: 'vitoria', km: 524}
    ]
  },
  {
    city: 'boa_vista',
    to: [
      {city: 'aracaju', km: 6000},
      {city: 'belem',   km: 6083},
      {city: 'belo_horizonte', km: 4736},
      {city: 'boa_vista', km: 0},
      {city: 'brasilia', km: 4275},
      {city: 'campo_grande', km: 3836},
      {city: 'cuiaba', km: 3142},
      {city: 'curitiba', km: 4821},
      {city: 'florianopolis', km: 5128},
      {city: 'fortaleza', km: 6548},
      {city: 'goiania', km: 4076},
      {city: 'joao_pessoa', km: 6593},
      {city: 'maceio', km: 6279},
      {city: 'manaus', km: 785},
      {city: 'natal', km: 6770},
      {city: 'palmas', km: 4926},
      {city: 'porto_alegre', km: 5348},
      {city: 'porto_velho', km: 1686},
      {city: 'recife', km: 6483},
      {city: 'rio_branco', km: 2230},
      {city: 'rio_de_janeiro', km: 5159},
      {city: 'salvador', km: 5794},
      {city: 'sao_luis', km: 6120},
      {city: 'sao_paulo', km: 4756},
      {city: 'teresina', km: 6052},
      {city: 'vitoria', km: 5261}
    ]
  },
  {
    city: 'brasilia',
    to: [
      {city: 'aracaju', km: 1652},
      {city: 'belem',   km: 2120},
      {city: 'belo_horizonte', km: 716},
      {city: 'boa_vista', km: 4275},
      {city: 'brasilia', km: 0},
      {city: 'campo_grande', km: 1134},
      {city: 'cuiaba', km: 1133},
      {city: 'curitiba', km: 1366},
      {city: 'florianopolis', km: 1673},
      {city: 'fortaleza', km: 2200},
      {city: 'goiania', km: 209},
      {city: 'joao_pessoa', km: 2245},
      {city: 'maceio', km: 1930},
      {city: 'manaus', km: 3490},
      {city: 'natal', km: 2422},
      {city: 'palmas', km: 973},
      {city: 'porto_alegre', km: 2027},
      {city: 'porto_velho', km: 2589},
      {city: 'recife', km: 2135},
      {city: 'rio_branco', km: 3123},
      {city: 'rio_de_janeiro', km: 1148},
      {city: 'salvador', km: 1446},
      {city: 'sao_luis', km: 2157},
      {city: 'sao_paulo', km: 1015},
      {city: 'teresina', km: 1789},
      {city: 'vitoria', km: 5261}
    ]
  },
  {
    city: 'campo_grande',
    to: [
      {city: 'aracaju', km: 2765},
      {city: 'belem',   km: 2942},
      {city: 'belo_horizonte', km: 1453},
      {city: 'boa_vista', km: 3836},
      {city: 'brasilia', km: 1134},
      {city: 'campo_grande', km: 0},
      {city: 'cuiaba', km: 694},
      {city: 'curitiba', km: 991},
      {city: 'florianopolis', km: 1298},
      {city: 'fortaleza', km: 3407},
      {city: 'goiania', km: 935},
      {city: 'joao_pessoa', km: 3357},
      {city: 'maceio', km: 3040},
      {city: 'manaus', km: 3051},
      {city: 'natal', km: 3534},
      {city: 'palmas', km: 1785},
      {city: 'porto_alegre', km: 1518},
      {city: 'porto_velho', km: 2150},
      {city: 'recife', km:3247 },
      {city: 'rio_branco', km: 2684},
      {city: 'rio_de_janeiro', km: 1444},
      {city: 'salvador', km: 2568},
      {city: 'sao_luis', km: 2979},
      {city: 'sao_paulo', km: 1014},
      {city: 'teresina', km: 2911},
      {city: 'vitoria', km: 1892}
    ]
  },
  {
    city: 'cuiaba',
    to: [
      {city: 'aracaju', km: 2775},
      {city: 'belem',   km: 2941},
      {city: 'belo_horizonte', km: 1594},
      {city: 'boa_vista', km: 3142},
      {city: 'brasilia', km: 1133},
      {city: 'campo_grande', km: 694},
      {city: 'cuiaba', km: 0},
      {city: 'curitiba', km: 1679},
      {city: 'florianopolis', km: 1986},
      {city: 'fortaleza', km: 3406},
      {city: 'goiania', km: 934},
      {city: 'joao_pessoa', km: 3366},
      {city: 'maceio', km: 3049},
      {city: 'manaus', km: 2357},
      {city: 'natal', km: 3543},
      {city: 'palmas', km: 1784},
      {city: 'porto_alegre', km: 2206},
      {city: 'porto_velho', km: 1456},
      {city: 'recife', km: 3255},
      {city: 'rio_branco', km: 1990},
      {city: 'rio_de_janeiro', km: 2017},
      {city: 'salvador', km: 2566},
      {city: 'sao_luis', km: 2978},
      {city: 'sao_paulo', km: 1614},
      {city: 'teresina', km: 2910},
      {city: 'vitoria', km: 2119}
    ]
  },
  {
    city: 'curitiba',
    to: [
      {city: 'aracaju', km: 2595},
      {city: 'belem',   km: 3193},
      {city: 'belo_horizonte', km: 1004},
      {city: 'boa_vista', km: 4821},
      {city: 'brasilia', km: 1366},
      {city: 'campo_grande', km: 991},
      {city: 'cuiaba', km: 1679},
      {city: 'curitiba', km: 0},
      {city: 'florianopolis', km: 300},
      {city: 'fortaleza', km: 3541},
      {city: 'goiania', km: 1186},
      {city: 'joao_pessoa', km: 3188},
      {city: 'maceio', km: 2871},
      {city: 'manaus', km: 4036},
      {city: 'natal', km: 3365},
      {city: 'palmas', km: 2036},
      {city: 'porto_alegre', km: 711},
      {city: 'porto_velho', km: 3135},
      {city: 'recife', km: 3078},
      {city: 'rio_branco', km: 3669},
      {city: 'rio_de_janeiro', km: 852},
      {city: 'salvador', km: 2385},
      {city: 'sao_luis', km: 3230},
      {city: 'sao_paulo', km: 408},
      {city: 'teresina', km: 3143},
      {city: 'vitoria', km: 1300}
    ]
  },
  {
    city: 'florianopolis',
    to: [
      {city: 'aracaju', km: 2892},
      {city: 'belem',   km: 3500},
      {city: 'belo_horizonte', km: 1301},
      {city: 'boa_vista', km: 5128},
      {city: 'brasilia', km: 1673},
      {city: 'campo_grande', km: 1298},
      {city: 'cuiaba', km: 1986},
      {city: 'curitiba', km: 300},
      {city: 'florianopolis', km: 0},
      {city: 'fortaleza', km: 3838},
      {city: 'goiania', km: 1493},
      {city: 'joao_pessoa', km: 3485},
      {city: 'maceio', km: 3168},
      {city: 'manaus', km: 4443},
      {city: 'natal', km: 3662},
      {city: 'palmas', km: 2336},
      {city: 'porto_alegre', km: 476},
      {city: 'porto_velho', km: 3442},
      {city: 'recife', km: 3375},
      {city: 'rio_branco', km: 3976},
      {city: 'rio_de_janeiro', km: 1144},
      {city: 'salvador', km: 2682},
      {city: 'sao_luis', km: 3537},
      {city: 'sao_paulo', km: 705},
      {city: 'teresina', km: 3450},
      {city: 'vitoria', km: 1597}
    ]
  },
  {
    city: 'fortaleza',
    to: [
      {city: 'aracaju', km: 1183},
      {city: 'belem',   km: 1610},
      {city: 'belo_horizonte', km: 2528},
      {city: 'boa_vista', km: 6548},
      {city: 'brasilia', km: 2200},
      {city: 'campo_grande', km: 3407},
      {city: 'cuiaba', km: 3406},
      {city: 'curitiba', km: 3541},
      {city: 'florianopolis', km: 3838},
      {city: 'fortaleza', km: 0},
      {city: 'goiania', km: 2482},
      {city: 'joao_pessoa', km: 688},
      {city: 'maceio', km: 1075},
      {city: 'manaus', km: 5763},
      {city: 'natal', km: 537},
      {city: 'palmas', km: 2035},
      {city: 'porto_alegre', km: 4242},
      {city: 'porto_velho', km: 4862},
      {city: 'recife', km: 800},
      {city: 'rio_branco', km: 5396},
      {city: 'rio_de_janeiro', km: 2805},
      {city: 'salvador', km: 1389},
      {city: 'sao_luis', km: 1070},
      {city: 'sao_paulo', km: 3127},
      {city: 'teresina', km: 634},
      {city: 'vitoria', km: 2397}
    ]
  },
  {
    city: 'goiania',
    to: [
      {city: 'aracaju', km: 1848},
      {city: 'belem',   km: 2017},
      {city: 'belo_horizonte', km: 906},
      {city: 'boa_vista', km: 4076},
      {city: 'brasilia', km: 209},
      {city: 'campo_grande', km: 935},
      {city: 'cuiaba', km: 934},
      {city: 'curitiba', km: 1186},
      {city: 'florianopolis', km: 1493},
      {city: 'fortaleza', km: 2482},
      {city: 'goiania', km: 0},
      {city: 'joao_pessoa', km: 2442},
      {city: 'maceio', km: 2125},
      {city: 'manaus', km: 3291},
      {city: 'natal', km: 2618},
      {city: 'palmas', km: 874},
      {city: 'porto_alegre', km: 1847},
      {city: 'porto_velho', km: 2390},
      {city: 'recife', km: 2332},
      {city: 'rio_branco', km: 2924},
      {city: 'rio_de_janeiro', km: 1338},
      {city: 'salvador', km: 1643},
      {city: 'sao_luis', km: 2054},
      {city: 'sao_paulo', km: 926},
      {city: 'teresina', km: 1986},
      {city: 'vitoria', km: 1428}
    ]
  },
  {
    city: 'joao_pessoa',
    to: [
      {city: 'aracaju', km: 611},
      {city: 'belem',   km: 2161},
      {city: 'belo_horizonte', km: 2171},
      {city: 'boa_vista', km: 6593},
      {city: 'brasilia', km: 2245},
      {city: 'campo_grande', km: 3357},
      {city: 'cuiaba', km: 3366},
      {city: 'curitiba', km: 3188},
      {city: 'florianopolis', km: 3485},
      {city: 'fortaleza', km: 688},
      {city: 'goiania', km: 2442},
      {city: 'joao_pessoa', km: 0},
      {city: 'maceio', km: 395},
      {city: 'manaus', km: 5808},
      {city: 'natal', km: 185},
      {city: 'palmas', km: 2253},
      {city: 'porto_alegre', km: 3889},
      {city: 'porto_velho', km: 4822},
      {city: 'recife', km: 120},
      {city: 'rio_branco', km: 5356},
      {city: 'rio_de_janeiro', km: 2448},
      {city: 'salvador', km: 949},
      {city: 'sao_luis', km: 1660},
      {city: 'sao_paulo', km: 2770},
      {city: 'teresina', km: 1224},
      {city: 'vitoria', km: 2001}
    ]
  },
  {
    city: 'maceio',
    to: [
      {city: 'aracaju', km: 294},
      {city: 'belem',   km: 2173},
      {city: 'belo_horizonte', km: 1854},
      {city: 'boa_vista', km: 6279},
      {city: 'brasilia', km: 1930},
      {city: 'campo_grande', km: 3040},
      {city: 'cuiaba', km: 3049},
      {city: 'curitiba', km: 2871},
      {city: 'florianopolis', km: 3168},
      {city: 'fortaleza', km: 1075},
      {city: 'goiania', km: 2125},
      {city: 'joao_pessoa', km: 395},
      {city: 'maceio', km: 0},
      {city: 'manaus', km: 5491},
      {city: 'natal', km: 572},
      {city: 'palmas', km: 1851},
      {city: 'porto_alegre', km: 3572},
      {city: 'porto_velho', km: 4505},
      {city: 'recife', km: 285},
      {city: 'rio_branco', km: 5039},
      {city: 'rio_de_janeiro', km: 2131},
      {city: 'salvador', km: 632},
      {city: 'sao_luis', km: 1672},
      {city: 'sao_paulo', km: 2453},
      {city: 'teresina', km: 1236},
      {city: 'vitoria', km: 1684}
    ]
  },
  {
    city: 'manaus',
    to: [
      {city: 'aracaju', km: 5215},
      {city: 'belem',   km: 5298},
      {city: 'belo_horizonte', km: 3951},
      {city: 'boa_vista', km: 785},
      {city: 'brasilia', km: 3490},
      {city: 'campo_grande', km: 3051},
      {city: 'cuiaba', km: 2357},
      {city: 'curitiba', km: 4036},
      {city: 'florianopolis', km: 4443},
      {city: 'fortaleza', km: 5763},
      {city: 'goiania', km: 3291},
      {city: 'joao_pessoa', km: 5808},
      {city: 'maceio', km: 5491},
      {city: 'manaus', km: 0},
      {city: 'natal', km: 5985},
      {city: 'palmas', km: 4141},
      {city: 'porto_alegre', km: 4563},
      {city: 'porto_velho', km: 901},
      {city: 'recife', km: 5698},
      {city: 'rio_branco', km: 1445},
      {city: 'rio_de_janeiro', km: 4374},
      {city: 'salvador', km: 5009},
      {city: 'sao_luis', km: 5335},
      {city: 'sao_paulo', km: 3971},
      {city: 'teresina', km: 5267},
      {city: 'vitoria', km: 4476}
    ]
  },
  {
    city: 'natal',
    to: [
      {city: 'aracaju', km: 788},
      {city: 'belem',   km: 2108},
      {city: 'belo_horizonte', km: 2348},
      {city: 'boa_vista', km: 6770},
      {city: 'brasilia', km: 2422},
      {city: 'campo_grande', km: 3534},
      {city: 'cuiaba', km: 3543},
      {city: 'curitiba', km: 3365},
      {city: 'florianopolis', km: 3662},
      {city: 'fortaleza', km: 537},
      {city: 'goiania', km: 2618},
      {city: 'joao_pessoa', km: 185},
      {city: 'maceio', km: 572},
      {city: 'manaus', km: 5985},
      {city: 'natal', km: 0},
      {city: 'palmas', km: 2345},
      {city: 'porto_alegre', km: 4066},
      {city: 'porto_velho', km: 4998},
      {city: 'recife', km: 297},
      {city: 'rio_branco', km: 5533},
      {city: 'rio_de_janeiro', km: 2625},
      {city: 'salvador', km: 1126},
      {city: 'sao_luis', km: 1607},
      {city: 'sao_paulo', km: 2947},
      {city: 'teresina', km: 1171},
      {city: 'vitoria', km: 2178}
    ]
  },
  {
    city: 'palmas',
    to: [
      {city: 'aracaju', km: 1662},
      {city: 'belem',   km: 1283},
      {city: 'belo_horizonte', km: 1690},
      {city: 'boa_vista', km: 4926},
      {city: 'brasilia', km: 973},
      {city: 'campo_grande', km: 1785},
      {city: 'cuiaba', km: 1784},
      {city: 'curitiba', km: 2036},
      {city: 'florianopolis', km: 2336},
      {city: 'fortaleza', km: 2035},
      {city: 'goiania', km: 874},
      {city: 'joao_pessoa', km: 2253},
      {city: 'maceio', km: 1851},
      {city: 'manaus', km: 4141},
      {city: 'natal', km: 2345},
      {city: 'palmas', km: 0},
      {city: 'porto_alegre', km: 2747},
      {city: 'porto_velho', km: 1711},
      {city: 'recife', km: 2058},
      {city: 'rio_branco', km: 3764},
      {city: 'rio_de_janeiro', km: 2124},
      {city: 'salvador', km: 1454},
      {city: 'sao_luis', km: 1386},
      {city: 'sao_paulo', km: 1776},
      {city: 'teresina', km: 1401},
      {city: 'vitoria', km: 2214}
    ]
  },
  {
    city: 'porto_alegre',
    to: [
      {city: 'aracaju', km: 3296},
      {city: 'belem',   km: 3852},
      {city: 'belo_horizonte', km: 1712},
      {city: 'boa_vista', km: 5348},
      {city: 'brasilia', km: 2027},
      {city: 'campo_grande', km: 1518},
      {city: 'cuiaba', km: 2206},
      {city: 'curitiba', km: 711},
      {city: 'florianopolis', km: 476},
      {city: 'fortaleza', km: 4242},
      {city: 'goiania', km: 1847},
      {city: 'joao_pessoa', km: 3889},
      {city: 'maceio', km: 3572},
      {city: 'manaus', km: 4563},
      {city: 'natal', km: 4066},
      {city: 'palmas', km: 2747},
      {city: 'porto_alegre', km: 0},
      {city: 'porto_velho', km: 3662},
      {city: 'recife', km: 3779},
      {city: 'rio_branco', km: 4196},
      {city: 'rio_de_janeiro', km: 1553},
      {city: 'salvador', km: 3090},
      {city: 'sao_luis', km: 3891},
      {city: 'sao_paulo', km: 1109},
      {city: 'teresina', km: 3804},
      {city: 'vitoria', km: 2001}
    ]
  },
  {
    city: 'porto_velho',
    to: [
      {city: 'aracaju', km: 4230},
      {city: 'belem',   km: 4397},
      {city: 'belo_horizonte', km: 3050},
      {city: 'boa_vista', km: 1686},
      {city: 'brasilia', km: 2589},
      {city: 'campo_grande', km: 2150},
      {city: 'cuiaba', km: 1456},
      {city: 'curitiba', km: 3135},
      {city: 'florianopolis', km: 3442},
      {city: 'fortaleza', km: 4862},
      {city: 'goiania', km: 2390},
      {city: 'joao_pessoa', km: 4822},
      {city: 'maceio', km: 4505},
      {city: 'manaus', km: 901},
      {city: 'natal', km: 4998},
      {city: 'palmas', km: 1711},
      {city: 'porto_alegre', km: 3662},
      {city: 'porto_velho', km: 0},
      {city: 'recife', km: 4712},
      {city: 'rio_branco', km: 544},
      {city: 'rio_de_janeiro', km: 3473},
      {city: 'salvador', km: 4023},
      {city: 'sao_luis', km: 4434},
      {city: 'sao_paulo', km: 3070},
      {city: 'teresina', km: 4366},
      {city: 'vitoria', km: 3575}
    ]
  },
  {
    city: 'recife',
    to: [
      {city: 'aracaju', km: 501},
      {city: 'belem',   km: 2074},
      {city: 'belo_horizonte', km: 2061},
      {city: 'boa_vista', km: 6483},
      {city: 'brasilia', km: 2135},
      {city: 'campo_grande', km: 3247},
      {city: 'cuiaba', km: 3255},
      {city: 'curitiba', km: 3078},
      {city: 'florianopolis', km: 3375},
      {city: 'fortaleza', km: 800},
      {city: 'goiania', km: 2332},
      {city: 'joao_pessoa', km: 120},
      {city: 'maceio', km: 285},
      {city: 'manaus', km: 5698},
      {city: 'natal', km: 297},
      {city: 'palmas', km: 2058},
      {city: 'porto_alegre', km: 3779},
      {city: 'porto_velho', km: 4712},
      {city: 'recife', km: 0},
      {city: 'rio_branco', km: 5243},
      {city: 'rio_de_janeiro', km: 2338},
      {city: 'salvador', km: 839},
      {city: 'sao_luis', km: 1573},
      {city: 'sao_paulo', km: 2660},
      {city: 'teresina', km: 1137},
      {city: 'vitoria', km: 1831}
    ]
  },
  {
    city: 'rio_branco',
    to: [
      {city: 'aracaju', km: 4763},
      {city: 'belem',   km: 4931},
      {city: 'belo_horizonte', km: 3584},
      {city: 'boa_vista', km: 2230},
      {city: 'brasilia', km: 3123},
      {city: 'campo_grande', km: 2684},
      {city: 'cuiaba', km: 1990},
      {city: 'curitiba', km: 3669},
      {city: 'florianopolis', km: 3976},
      {city: 'fortaleza', km: 5396},
      {city: 'goiania', km: 2924},
      {city: 'joao_pessoa', km: 5356},
      {city: 'maceio', km: 5039},
      {city: 'manaus', km: 1445},
      {city: 'natal', km: 5533},
      {city: 'palmas', km: 3764},
      {city: 'porto_alegre', km: 4196},
      {city: 'porto_velho', km: 544},
      {city: 'recife', km: 5243},
      {city: 'rio_branco', km: 0},
      {city: 'rio_de_janeiro', km: 4007},
      {city: 'salvador', km: 4457},
      {city: 'sao_luis', km: 4968},
      {city: 'sao_paulo', km: 3604},
      {city: 'teresina', km: 4900},
      {city: 'vitoria', km: 4109}
    ]
  },
  {
    city: 'rio_de_janeiro',
    to: [
      {city: 'aracaju', km: 1855},
      {city: 'belem',   km: 3250},
      {city: 'belo_horizonte', km: 434},
      {city: 'boa_vista', km: 5159},
      {city: 'brasilia', km: 1148},
      {city: 'campo_grande', km: 1444},
      {city: 'cuiaba', km: 2017},
      {city: 'curitiba', km: 852},
      {city: 'florianopolis', km: 1144},
      {city: 'fortaleza', km: 2805},
      {city: 'goiania', km: 1338},
      {city: 'joao_pessoa', km: 2448},
      {city: 'maceio', km: 2131},
      {city: 'manaus', km: 4374},
      {city: 'natal', km: 2625},
      {city: 'palmas', km: 2124},
      {city: 'porto_alegre', km: 1553},
      {city: 'porto_velho', km: 3473},
      {city: 'recife', km: 2338},
      {city: 'rio_branco', km: 4007},
      {city: 'rio_de_janeiro', km: 0},
      {city: 'salvador', km: 1649},
      {city: 'sao_luis', km: 3015},
      {city: 'sao_paulo', km: 429},
      {city: 'teresina', km: 2579},
      {city: 'vitoria', km: 521}
    ]
  },
  {
    city: 'salvador',
    to: [
      {city: 'aracaju', km: 356},
      {city: 'belem',   km: 2100},
      {city: 'belo_horizonte', km: 1372},
      {city: 'boa_vista', km: 5794},
      {city: 'brasilia', km: 1446},
      {city: 'campo_grande', km: 2568},
      {city: 'cuiaba', km: 2566},
      {city: 'curitiba', km: 2385},
      {city: 'florianopolis', km: 2682},
      {city: 'fortaleza', km: 1389},
      {city: 'goiania', km: 1643},
      {city: 'joao_pessoa', km: 949},
      {city: 'maceio', km: 632},
      {city: 'manaus', km: 5009},
      {city: 'natal', km: 1126},
      {city: 'palmas', km: 1454},
      {city: 'porto_alegre', km: 3090},
      {city: 'porto_velho', km: 4023},
      {city: 'recife', km: 839},
      {city: 'rio_branco', km: 4457},
      {city: 'rio_de_janeiro', km: 1649},
      {city: 'salvador', km: 0},
      {city: 'sao_luis', km: 1599},
      {city: 'sao_paulo', km: 1962},
      {city: 'teresina', km: 1163},
      {city: 'vitoria', km: 1202}
    ]
  },
  {
    city: 'sao_luis',
    to: [
      {city: 'aracaju', km: 1578},
      {city: 'belem',   km: 806},
      {city: 'belo_horizonte', km: 2738},
      {city: 'boa_vista', km: 6120},
      {city: 'brasilia', km: 2157},
      {city: 'campo_grande', km: 2979},
      {city: 'cuiaba', km: 2978},
      {city: 'curitiba', km: 3230},
      {city: 'florianopolis', km: 3537},
      {city: 'fortaleza', km: 1070},
      {city: 'goiania', km: 2054},
      {city: 'joao_pessoa', km: 1660},
      {city: 'maceio', km: 1672},
      {city: 'manaus', km: 5335},
      {city: 'natal', km: 1607},
      {city: 'palmas', km: 1386},
      {city: 'porto_alegre', km: 3891},
      {city: 'porto_velho', km: 4434},
      {city: 'recife', km: 1573},
      {city: 'rio_branco', km: 4968},
      {city: 'rio_de_janeiro', km: 3015},
      {city: 'salvador', km: 1599},
      {city: 'sao_luis', km: 0},
      {city: 'sao_paulo', km: 2970},
      {city: 'teresina', km: 446},
      {city: 'vitoria', km: 2607}
    ]
  },
  {
    city: 'sao_paulo',
    to: [
      {city: 'aracaju', km: 2187},
      {city: 'belem',   km: 2933},
      {city: 'belo_horizonte', km: 586},
      {city: 'boa_vista', km: 4756},
      {city: 'brasilia', km: 1015},
      {city: 'campo_grande', km: 1014},
      {city: 'cuiaba', km: 1614},
      {city: 'curitiba', km: 408},
      {city: 'florianopolis', km: 705},
      {city: 'fortaleza', km: 3127},
      {city: 'goiania', km: 926},
      {city: 'joao_pessoa', km: 2770},
      {city: 'maceio', km: 2453},
      {city: 'manaus', km: 3971},
      {city: 'natal', km: 2947},
      {city: 'palmas', km: 1776},
      {city: 'porto_alegre', km: 1109},
      {city: 'porto_velho', km: 3070},
      {city: 'recife', km: 2660},
      {city: 'rio_branco', km: 3604},
      {city: 'rio_de_janeiro', km: 429},
      {city: 'salvador', km: 1962},
      {city: 'sao_luis', km: 2970},
      {city: 'sao_paulo', km: 0},
      {city: 'teresina', km: 2792},
      {city: 'vitoria', km: 882}
    ]
  },
  {
    city: 'teresina',
    to: [
      {city: 'aracaju', km: 1142},
      {city: 'belem',   km: 947},
      {city: 'belo_horizonte', km: 2302},
      {city: 'boa_vista', km: 6052},
      {city: 'brasilia', km: 1789},
      {city: 'campo_grande', km: 2911},
      {city: 'cuiaba', km: 2910},
      {city: 'curitiba', km: 3143},
      {city: 'florianopolis', km: 3450},
      {city: 'fortaleza', km: 634},
      {city: 'goiania', km: 1986},
      {city: 'joao_pessoa', km: 1224},
      {city: 'maceio', km: 1236},
      {city: 'manaus', km: 5267},
      {city: 'natal', km: 1171},
      {city: 'palmas', km: 1401},
      {city: 'porto_alegre', km: 3804},
      {city: 'porto_velho', km: 4366},
      {city: 'recife', km: 1137},
      {city: 'rio_branco', km: 4900},
      {city: 'rio_de_janeiro', km: 2579},
      {city: 'salvador', km: 1163},
      {city: 'sao_luis', km: 446},
      {city: 'sao_paulo', km: 2792},
      {city: 'teresina', km: 0},
      {city: 'vitoria', km: 2171}
    ]
  },
  {
    city: 'vitoria',
    to: [
      {city: 'aracaju', km: 1408},
      {city: 'belem',   km: 3108},
      {city: 'belo_horizonte', km: 524},
      {city: 'boa_vista', km: 5261},
      {city: 'brasilia', km: 1239},
      {city: 'campo_grande', km: 1892},
      {city: 'cuiaba', km: 2119},
      {city: 'curitiba', km: 1300},
      {city: 'florianopolis', km: 1597},
      {city: 'fortaleza', km: 2397},
      {city: 'goiania', km: 1428},
      {city: 'joao_pessoa', km: 2001},
      {city: 'maceio', km: 1684},
      {city: 'manaus', km: 4476},
      {city: 'natal', km: 2178},
      {city: 'palmas', km: 2214},
      {city: 'porto_alegre', km: 2001},
      {city: 'porto_velho', km: 3575},
      {city: 'recife', km: 1831},
      {city: 'rio_branco', km: 4109},
      {city: 'rio_de_janeiro', km: 521},
      {city: 'salvador', km: 1202},
      {city: 'sao_luis', km: 2607},
      {city: 'sao_paulo', km: 882},
      {city: 'teresina', km: 2171},
      {city: 'vitoria', km: 0}
    ]
  }
];

module.exports = cities;
