var cities = [
  {
    city: 'aracaju',
    to: [
      {city: 'aracaju', km: 0},
      {city: 'belem',   km: 2079},
      {city: 'belo_horizonte', km: 1578},
      {city: 'boa_vista', km: 6000},
      {city: 'brasilia', km: 1652},
      {city: 'campo_grande', km: 2765},
      {city: 'cuiaba', km: 2775},
      {city: 'curitiba', km: 2595},
      {city: 'florianopolis', km: 2892},
      {city: 'fortaleza', km: 1183},
      {city: 'goiania', km: 1848},
      {city: 'joao_pessoa', km: 611},
      {city: 'maceio', km: 294},
      {city: 'manaus', km: 5215},
      {city: 'natal', km: 788},
      {city: 'palmas', km: 1662},
      {city: 'porto_alegre', km: 3296},
      {city: 'porto_velho', km: 4230},
      {city: 'recife', km: 501},
      {city: 'rio_branco', km: 4763},
      {city: 'rio_de_janeiro', km: 1855},
      {city: 'salvador', km: 356},
      {city: 'sao_luis', km: 1578},
      {city: 'sao_paulo', km: 2187},
      {city: 'teresina', km: 1142},
      {city: 'vitoria', km: 1408}
    ]
  },
  {
    city: 'belem',
    to: [
      {city: 'aracaju', km: 2079},
      {city: 'belem',   km: 0},
      {city: 'belo_horizonte', km: 2824},
      {city: 'boa_vista', km: 6083},
      {city: 'brasilia', km: 2120},
      {city: 'campo_grande', km: 2942},
      {city: 'cuiaba', km: 2941},
      {city: 'curitiba', km: 3193},
      {city: 'florianopolis', km: 3500},
      {city: 'fortaleza', km: 1301},
      {city: 'goiania', km: 2017},
      {city: 'joao_pessoa', km: 2161},
      {city: 'maceio', km: 2173},
      {city: 'manaus', km: 5298},
      {city: 'natal', km: 2108},
      {city: 'palmas', km: 1283},
      {city: 'porto_alegre', km: 3852},
      {city: 'porto_velho', km: 4397},
      {city: 'recife', km: 2074},
      {city: 'rio_branco', km: 4931},
      {city: 'rio_de_janeiro', km: 3250},
      {city: 'salvador', km: 2100},
      {city: 'sao_luis', km: 806},
      {city: 'sao_paulo', km: 2933},
      {city: 'teresina', km: 947},
      {city: 'vitoria', km: 3108}
    ]
  },
  {
    city: 'belo_horizonte',
    to: [
      {city: 'aracaju', km: 1578},
      {city: 'belem',   km: 2824},
      {city: 'belo_horizonte', km: 0},
      {city: 'boa_vista', km: 4736},
      {city: 'brasilia', km: 716},
      {city: 'campo_grande', km: 1453},
      {city: 'cuiaba', km: 1594},
      {city: 'curitiba', km: 1004},
      {city: 'florianopolis', km: 1301},
      {city: 'fortaleza', km: 2528},
      {city: 'goiania', km: 906},
      {city: 'joao_pessoa', km: 2171},
      {city: 'maceio', km: 1854},
      {city: 'manaus', km: 3951},
      {city: 'natal', km: 2348},
      {city: 'palmas', km: 1690},
      {city: 'porto_alegre', km: 1712},
      {city: 'porto_velho', km: 3050},
      {city: 'recife', km: 2061},
      {city: 'rio_branco', km: 3584},
      {city: 'rio_de_janeiro', km: 434},
      {city: 'salvador', km: 1372},
      {city: 'sao_luis', km: 2738},
      {city: 'sao_paulo', km: 586},
      {city: 'teresina', km: 2302},
      {city: 'vitoria', km: 524}
    ]
  },
  {
    city: 'boa_vista',
    to: [
      {city: 'aracaju', km: 6000},
      {city: 'belem',   km: 6083},
      {city: 'belo_horizonte', km: 4736},
      {city: 'boa_vista', km: 0},
      {city: 'brasilia', km: 4275},
      {city: 'campo_grande', km: 3836},
      {city: 'cuiaba', km: 3142},
      {city: 'curitiba', km: 4821},
      {city: 'florianopolis', km: 5128},
      {city: 'fortaleza', km: 6548},
      {city: 'goiania', km: 4076},
      {city: 'joao_pessoa', km: 6593},
      {city: 'maceio', km: 6279},
      {city: 'manaus', km: 785},
      {city: 'natal', km: 6770},
      {city: 'palmas', km: 4926},
      {city: 'porto_alegre', km: 5348},
      {city: 'porto_velho', km: 1686},
      {city: 'recife', km: 6483},
      {city: 'rio_branco', km: 2230},
      {city: 'rio_de_janeiro', km: 5159},
      {city: 'salvador', km: 5794},
      {city: 'sao_luis', km: 6120},
      {city: 'sao_paulo', km: 4756},
      {city: 'teresina', km: 6052},
      {city: 'vitoria', km: 5261}
    ]
  }
];

module.exports = cities;